#!/bin/bash

log() {
    tee "${PLOTTER_LOGDIR:=/tmp}/$(date +'%Y-%m-%d_%H.%M.%S').log"
}

filter() {
    if [ "$FILTER" == "yes" ]; then
        grep -v "Bucket"
    else
        cat
    fi
}


plot_cmd="chia plots create"

$plot_cmd $@ | log | filter
